Fix validation warnings
nvpro-samples/vk_video_samples pull request #57
Opened 2023-09-20 14:02 UTC by charlie-ht

There remain some less serious warnings after this series, but to fix some of the more difficult ones, changes in how the image handling and download happens were required.

Those commits start at "Use concurrent sharing when the transfer queue != decode queue". I'd like some review that this is an OK direction to take the sample app in before going much further.

/cc @zlatinski

2023-11-03 00:22 UTC, zlatinski requested changes
Thank you, Charlie, for the changes.

2023-11-03 00:22 UTC, zlatinski commented on vk_video_decoder/libs/VkCodecUtils/VulkanVideoProcessor.cpp
> +        VkBufferResource::Create(m_vkDevCtx,
Are we creating and destroying resources with each frame here?
Also, why is using a buffer copy better than an image copy?

2024-03-11 19:50 UTC, zlatinski commented
Hi @charlie-ht, Can you please rebase your fixes against the ToT? Sorry, it took so long!

2024-03-11 20:52 UTC, BattleAxeVR commented
I so look forward to using this so I can have 100% clean validation logs in my engine. It's also worrisome that some of the data wasn't even passed like the HEVC profile of the video in question during certain buffer creation, I had started to fix that but realized it needed some more serious refactoring to access that data from higher up the callstack.

2024-03-24 19:23 UTC, charlie-ht commented
> Hi @charlie-ht, Can you please rebase your fixes against the ToT? Sorry, it took so long!

Hi @zlatinski - unfortunately main has moved along in a way that makes a lot of this conflict. Perhaps best to close this one, and I'll try and find some time to pick over any validation errors that remain in the latest main branch.

https://github.com/nvpro-samples/vk_video_samples/pull/69 partly overlaps some of this work (the transfer queue exposure). Can you merge those fixes for AMD into the encode branch and the main branch?

2026-03-10 09:59 UTC, zlatinski commented
This is already outdated. The validation layer issues should have been addressed at the ToT.

2026-03-10 09:59 UTC, closed without merging